name: deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clear npm cache
        run: npm cache clean --force

      - uses: actions/checkout@v3

      - name: Use Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install NPM
        run: |
          npm install

      - name: Run Typescript check
        run: |
          npm run type-check

      - name: Run Test
        run: |
          npm run test

      - name: Run Build
        run: |
          npm run build